### ISSUE TITLE
task 7 failed

### ISSUE THREAD

**Issue by kelly-clark** [CSOgroup/TAD-benchmarking-scripts#1]
Hi!

I'm trying to use the R script for MoC to compare a few TAD callers. I'm getting an error that says this:

`  task 7 failed - "all(all_matches == all_matches_2) is not TRUE"
`

I'm using as my input files two bed files of different chr1 TAD calls. Would the error I'm getting be an issue related to my input format?

Thanks,
Kelly

**Comment by marzuf** [comment]
Dear Kelly,

Thanks for your interest. Unfortunately I did not succeed to reproduce this error with some toy data. Could you send me your 2 bed files so that I could have a look (marie.zufferey.1[at]unil.ch) ?

Thanks !
Best regards,

Marie

**Comment by kelly-clark** [comment]
Hi Marie,
Thanks for getting back to me! I actually just realized that my input was the issue, so problem solved.
Best,
Kelly
